{
  "bucketName": "ecom-g13",
  "sseAlgorithm": null,
  "ongoingRestore": false,
  "storageClass": null,
  "sseCustomerAlgorithm": null,
  "contentDisposition": null,
  "contentEncoding": null,
  "contentType": "text/csv",
  "key": "Account Data.csv",
  "sseCustomerKeyMd5": null,
  "contentMD5": null,
  "requesterCharged": false,
  "replicationStatus": null,
  "cacheControl": null,
  "httpExpiresDate": null,
  "versionId": null,
  "sseAwsKmsKeyId": null,
  "restoreExpirationTime": null,
  "expirationTimeRuleId": null,
  "expirationTime": null,
  "contentLanguage": null,
  "contentLength": 491,
  "etag": "f7239ba487996e2182c47e3f6eb77df3",
  "lastModified": |2022-01-04T11:26:50|,
  "userMetadata": {},
  "redirectLocation": null
}