{
  "bucketName": "ecom-g13",
  "sseAlgorithm": null,
  "ongoingRestore": false,
  "storageClass": null,
  "sseCustomerAlgorithm": null,
  "contentDisposition": null,
  "contentEncoding": null,
  "contentType": "text/csv",
  "key": "Inventory Data.csv",
  "sseCustomerKeyMd5": null,
  "contentMD5": null,
  "requesterCharged": false,
  "replicationStatus": null,
  "cacheControl": null,
  "httpExpiresDate": null,
  "sseAwsKmsKeyId": null,
  "versionId": null,
  "restoreExpirationTime": null,
  "expirationTimeRuleId": null,
  "expirationTime": null,
  "contentLanguage": null,
  "contentLength": 215,
  "etag": "25768b3524f2b8147d852ee6d92e2128",
  "lastModified": |2022-01-04T11:52:38|,
  "userMetadata": {},
  "redirectLocation": null
}